/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ahorcado;

import sun.security.util.Length;

/**
 *
 * @author Pablo
 */
public class AhorcadoFrame extends javax.swing.JFrame {

    /**
     * Creates new form AhorcadoFrame
     */
    
    Partida partida = new Partida();
    String palabra1 = "";
    String palabra2 = "";
    Jugador jugador1 = partida.getJugador1();
    Jugador jugador2 = partida.getJugador2();
    
    public AhorcadoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        palabraSugerida1 = new javax.swing.JTextField();
        palabraSugerida2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        palabra2Label = new javax.swing.JLabel();
        palabra1Label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        letra1jText = new javax.swing.JTextField();
        letra2jText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        letras1jLabel = new javax.swing.JLabel();
        letras2jLabel = new javax.swing.JLabel();
        victorias1Label = new javax.swing.JLabel();
        victorias2Label = new javax.swing.JLabel();
        sugerirDeNuevoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Victorias jugador1:");

        jLabel2.setText("Victorias jugador2: ");

        jLabel3.setText("Palabra sugerida:");

        jLabel4.setText("Palabra sugerida:");

        palabraSugerida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabraSugerida1ActionPerformed(evt);
            }
        });

        palabraSugerida2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabraSugerida2ActionPerformed(evt);
            }
        });

        palabra2Label.setText("PALABRA A DESCRIFRAR");

        palabra1Label.setText("PALABRA A DESCRIFRAR");

        jLabel7.setText("Introducir letra:");

        jLabel8.setText("Introducir letra:");

        letra1jText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra1jTextActionPerformed(evt);
            }
        });

        letra2jText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra2jTextActionPerformed(evt);
            }
        });

        jLabel9.setText("Letras intentadas:");

        jLabel10.setText("Letras intentadas:");

        victorias1Label.setText("0");

        victorias2Label.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(palabraSugerida1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(victorias1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(palabraSugerida2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(victorias2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(palabra1Label)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(letra1jText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addComponent(letras1jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(letra2jText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(palabra2Label)
                            .addComponent(jLabel10)
                            .addComponent(letras2jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(sugerirDeNuevoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addComponent(victorias1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(victorias2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(palabraSugerida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabraSugerida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(sugerirDeNuevoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palabra2Label)
                    .addComponent(palabra1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(letra1jText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra2jText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(letras1jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letras2jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void palabraSugerida2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabraSugerida2ActionPerformed
        // TODO add your handling code here:
        String guess = "";
        String ast = "";
        for( int i=0; i < palabraSugerida2.getText().length(); i++)
        {
            guess += "_ ";
            ast += "*";
        }
            
        palabra1Label.setText(guess);
        palabra1 = palabraSugerida2.getText();
        palabraSugerida2.setText(ast);
        sugerirDeNuevoLabel.setText("");
    }//GEN-LAST:event_palabraSugerida2ActionPerformed

    private void letra2jTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra2jTextActionPerformed
        // TODO add your handling code here:
        String letra = letra2jText.getText();
        if(letra.length() == 1 &&  !jugador2.letrasIntentadas.contains(letra))
        {
            if(palabra2.contains(letra))
            {
                for (int i = 0; i <palabra2.length(); i++) {
                    if(palabra2.charAt(i) == letra.charAt(0))
                    {
                        palabra2Label.setText(palabra2Label.getText().substring(0, 2*i) 
                                                + letra 
                                                + palabra2Label.getText().substring(2*i + 1));
                    }
                }
            }
            else 
            {
                jugador2.letrasIntentadas.add(letra);
                letras2jLabel.setText(jugador2.mostrarLetrasIntentadas());
            }
            
        }
        
        
        if(!palabra2Label.getText().contains("_"))
        {
            jugador2.setVictorias(jugador2.getVictorias() + 1);
            victorias2Label.setText("" + jugador2.getVictorias());
            
            if(jugador2.getVictorias() == 3)
            {
                sugerirDeNuevoLabel.setText("JUGADOR 2 GANA");
                partida = new Partida();
                jugador1 = new Jugador();
                jugador2 = new Jugador();
                palabra1Label.setText("SUGERIR NUEVA PALABRA");
                palabra2Label.setText("SUGERIR NUEVA PALABRA");
                victorias1Label.setText("0");
                victorias2Label.setText("0");
                letras1jLabel.setText("");
                letras2jLabel.setText("");
                
            }
            else{
            
                letra2jText.setEditable(false);
                letra1jText.setEditable(false);

                sugerirDeNuevoLabel.setText("INTRODUCE UNA PALABRA JUGADOR 1");
                jugador2.borrarLetrasIntentadas();
                letras2jLabel.setText("");
            }
        }
        
        letra2jText.setEditable(false);
        letra1jText.setEditable(true);
        
    }//GEN-LAST:event_letra2jTextActionPerformed

    private void palabraSugerida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabraSugerida1ActionPerformed
        // TODO add your handling code here:
        String guess = "";
        String ast = "";
        for( int i=0; i < palabraSugerida1.getText().length(); i++)
        {
            guess += "_ ";
            ast += "*";
        }
            
        palabra2Label.setText(guess);
        palabra2 = palabraSugerida1.getText();
        palabraSugerida1.setText(ast);
        sugerirDeNuevoLabel.setText("");
    }//GEN-LAST:event_palabraSugerida1ActionPerformed

    private void letra1jTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra1jTextActionPerformed
        // TODO add your handling code here:
        String letra = letra1jText.getText();
        if(letra.length() == 1 && !jugador2.letrasIntentadas.contains(letra))
        {
            if(palabra1.contains(letra) )
            {
                for (int i = 0; i <palabra1.length(); i++) {
                    if(palabra1.charAt(i) == letra.charAt(0))
                    {
                        palabra1Label.setText(palabra1Label.getText().substring(0, 2*i) 
                                                + letra 
                                                + palabra1Label.getText().substring(2*i + 1));
                    }
                }
            }
            else 
            {
                jugador1.letrasIntentadas.add(letra);
                letras1jLabel.setText(jugador1.mostrarLetrasIntentadas());
            }
            
        }
       
        
        if(!palabra1Label.getText().contains("_"))
        {
            jugador1.setVictorias(jugador1.getVictorias() + 1);
            victorias1Label.setText("" + jugador1.getVictorias());
            
            if(jugador1.getVictorias() == 3)
            {
                sugerirDeNuevoLabel.setText("JUGADOR 1 GANA");
                partida = new Partida();
                jugador1 = new Jugador();
                jugador2 = new Jugador();
                palabra1Label.setText("SUGERIR NUEVA PALABRA");
                palabra2Label.setText("SUGERIR NUEVA PALABRA");
                victorias1Label.setText("0");
                victorias2Label.setText("0");
                letras1jLabel.setText("");
                letras2jLabel.setText("");
                
            }
            else
            {
            letra2jText.setEditable(false);
            letra1jText.setEditable(false);
            
            sugerirDeNuevoLabel.setText("INTRODUCE UNA PALABRA JUGADOR 2");
            jugador1.borrarLetrasIntentadas();
            letras1jLabel.setText("");
            }
            
        }

         
        letra1jText.setEditable(false);
        letra2jText.setEditable(true);
    }//GEN-LAST:event_letra1jTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AhorcadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AhorcadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AhorcadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AhorcadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AhorcadoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField letra1jText;
    private javax.swing.JTextField letra2jText;
    private javax.swing.JLabel letras1jLabel;
    private javax.swing.JLabel letras2jLabel;
    private javax.swing.JLabel palabra1Label;
    private javax.swing.JLabel palabra2Label;
    private javax.swing.JTextField palabraSugerida1;
    private javax.swing.JTextField palabraSugerida2;
    private javax.swing.JLabel sugerirDeNuevoLabel;
    private javax.swing.JLabel victorias1Label;
    private javax.swing.JLabel victorias2Label;
    // End of variables declaration//GEN-END:variables
}
